development:
  host: 127.0.0.1
  database: kor_development
  encoding: utf8
  reconnect: true
  # adapter: postgresql
  # username: postgres
  adapter: mysql2
  username: root
  password: root
  collation: utf8_general_ci

  elastic:
    host: 127.0.0.1
    port: 9200
    index: kor_development

test:
  host: 127.0.0.1
  database: kor_test
  encoding: utf8
  reconnect: true
  # adapter: postgresql
  # username: postgres
  adapter: mysql2
  username: root
  password: root
  encoding: utf8
  collation: utf8_general_ci

  elastic:
    host: 127.0.0.1
    port: 9200
    index: kor_test

production:
  adapter: mysql2
  host: 127.0.0.1
  database: kor_production
  username: root
  password: root
  encoding: utf8
  collation: utf8_general_ci
  reconnect: true

  elastic:
    host: 127.0.0.1
    port: 9200
    index: kor
