---
development:
  maintainer: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    name: Example Organization
    mail: admin@example.com
    legal_text: Beispieltext
    about_text: Beispieltext
    help_text: ''
    repository_uuid: 0376c22c-7a95-42ef-8873-76d24a2311c5
  host: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    protocol: http
    host: example.com
    port: '80'
  mail: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    host: 127.0.0.1
    port: '25'
    sender_name: ''
    sender_address: ''
    domain: localhost
    enable_starttls_auto: false
  app: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    default_home_page: "/entities"
    max_foreground_group_download_size: '10'
    max_file_upload_size: '100'
    current_history_length: '5'
    gallery: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      primary_relations:
      - Bilddatei zu Werk
      secondary_relations:
      - wurde geschaffen von
    welcome_title: "*This text can be configured via the general settings*"
    welcome_text: "*This text can be configured via the general settings*\r\n\r\n*bla*
      blub"
    default_locale: en
    source_code_url: http://download.coneda.net/releases/coneda-kor.v{{version}}.tar.gz
    warning_characters: "aaa\r\naa[0-9]aa\r\nb{1,5}"
  help: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    component_search: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      component_search: ''
    entities: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      index: ''
      multi_upload: ''
      gallery: ''
    authentication: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      form: ''
    users: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      edit_self: ''
    authority_group_categories: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      index: ''
    user_groups: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      index: ''
    tools: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      clipboard: ''
  auth:
    session_lifetime: 7200
    publishment_lifetime: 14
    default_groups: []
  mail_delivery_method: smtp
  logging:
    file: log/kor.log
    level: debug
  umask: 2
  cache_dir: tmp/cache
  tmp_dir: tmp/kor
  kind_settings:
    defaults:
      dating_label: Datierung
      name_label: Name
      distinct_name_label: Eindeutiger Name
  limits:
    max_file_upload_size: 30
    max_download_group_size: 80
  search:
    entity_name: Name / Titel / UUID
  dev:
    value_a: default.all
    value_b: default.all
